{
 "title": "1. Cluster overview",
 "tags": [ "INFRASTRUCTURE_ENG" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_selected",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "node_filter",
    "label": "node_filter",
    "query": "cluster-ops-node.*,cluster-ops-master.*,gw.*"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>Cluster overview</span>\n</div>"
   }
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}[5m])) / sum (machine_cpu_cores{node=~\"$node_selected\", node=~\"$node_filter\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) / sum (machine_memory_bytes{node=~\"$node_selected\", node=~\"$node_filter\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) * 100"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node_selected\", node=~\"$node_filter\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"})",
     "legendFormat": "node in error (status false)"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"unknown\",node=~\"$node_selected\", node=~\"$node_filter\"})",
     "legendFormat": "node stopped (status unknown)"
    }
   ]
  },
  {
   "title": "Out of Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$Node\", status!=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", status!=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "High-level overview of node health",
   "type": "text",
   "gridPos": { "h": 13, "w": 5, "x": 8, "y": 8 },
   "options": {
    "content": "\n# Condition to be checked \n\nFollowing indicators provide information about risk that scheduler could not place pods on node\n\n    OutOfDisk \n    Ready (node is ready to accept pods) / replaced by unchedulable, unavailable\n    MemoryPressure (node memory is too low)\n    PIDPressure (too many running processes)\n    DiskPressure (remaining disk capacity is too low)\n    NetworkUnavailable\n\n\n\n"
   }
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status!=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status!=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "Unschedulable node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node_selected\", node=~\"$node_filter\"})"
    }
   ]
  },
  {
   "title": "Node STOPPED",
   "type": "table-old",
   "description": "condition=\"Ready\" / status=\"unknown\"",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(kube_node_status_condition{condition=\"Ready\",status=\"unknown\",node=~\"$node_selected\", node=~\"$node_filter\"}) > 0",
     "legendFormat": "{{node{ '}}' }} "
    }
   ]
  },
  {
   "title": "Node UNAVAILABLE / ERROR",
   "type": "table-old",
   "description": "condition=\"Ready\" / status=\"false\"",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "(kube_node_status_condition{condition=\"Ready\",status=\"false\",node=~\"$node_selected\", node=~\"$node_filter\"}) > 0",
     "legendFormat": "{{node{ '}}' }} "
    }
   ]
  },
  { "title": "NODE (selected) CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Node CPU usage percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\", node=~\"$node_selected\", node=~\"$node_filter\"}[10m])) by (node) / sum (machine_cpu_cores{node=~\"$node_selected\", node=~\"$node_filter\"}) by (node) *100",
     "legendFormat": "{{node{ '}}' }}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{node=~\"$node_selected\", node=~\"$node_filter\"}[10m])) by (node) ",
     "legendFormat": "{{node{ '}}' }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\",container!=\"\", resource=\"cpu\"}) by ( node,pod)",
     "legendFormat": "cpu request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\",container!=\"\", resource=\"cpu\"}) by ( node,pod)",
     "legendFormat": "cpu limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\", container!=\"\"}[10m])) by (node,pod)",
     "legendFormat": "cpu values"
    }
   ]
  },
  {
   "title": "NODE (selected) Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node memory usage percentage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) by (node) / sum (machine_memory_bytes{node=~\"$node_selected\", node=~\"$node_filter\"}) by (node) * 100",
       "legendFormat": "{{node{ '}}' }}"
      }
     ]
    },
    {
     "title": "allocatable memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_node_status_allocatable{node=~\"$node_selected\"}"
      }
     ]
    },
    {
     "title": "Node memory usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 40 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) by (node)",
       "legendFormat": "{{node{ '}}' }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\",container!=\"\", resource=\"memory\"}) by ( node, pod)",
       "legendFormat": "cpu request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\",container!=\"\", resource=\"memory\"}) by (node, pod)",
       "legendFormat": "cpu limit"
      },
      {
       "expr": "sum(container_memory_usage_bytes{node=~\"$node_selected\",node=~\"$node_filter\", pod!=\"\", container!=\"\"}) by (node, pod)",
       "legendFormat": "cpu values"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE (selected) Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node filesystem usage percentage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",node=~\"$node_selected\", node=~\"$node_filter\"}) by (node) * 100",
       "legendFormat": "{{node{ '}}' }}"
      }
     ]
    }
   ]
  },
  {
   "title": "NODE (selected) Net",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{node=~\"$node_selected\", node=~\"$node_filter\"}[10m])) by (node)",
       "legendFormat": "-> {{node{ '}}' }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{node=~\"$node_selected\", node=~\"$node_filter\"}[10m])) by (node)",
       "legendFormat": "<- {{node{ '}}' }}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{node=~\"$node_selected\", node=~\"$node_filter\" }[5m])) by (node, pod)",
       "legendFormat": "{{node{ '}}' }} / {{pod{ '}}' }}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 11, "w": 21, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{node=~\"$node_selected\", node=~\"$node_filter\"}[5m])) by (node, pod)",
       "legendFormat": "{{node{ '}}' }} / {{pod{ '}}' }}"
      }
     ]
    }
   ]
  },
  { "title": "PODs from the selected NODE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pods CPU usage (10m avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod!=\"Value\",node=~\"$node_selected\",node=~\"$node_filter\"}[10m])) by (pod)",
     "legendFormat": "{{pod{ '}}' }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{image!=\"\",node=~\"$node_selected\",node=~\"$node_filter\",container!=\"POD\",container!=\"\"}) by (pod)",
     "legendFormat": "{{pod{ '}}' }}"
    }
   ]
  },
  {
   "title": "POD present on node @ the end of time range",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",node=~\"$node_selected\", node=~\"$node_filter\", pod!~\"\"}) by (node,pod)",
     "legendFormat": "{{pod{ '}}' }} "
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node_selected\", node=~\"$node_filter\", pod!~\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod{ '}}' }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",node=~\"$node_selected\", node=~\"$node_filter\", pod!~\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod_name{ '}}' }}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",node=~\"$node_selected\", node=~\"$node_filter\", pod!~\"\"}[1m])) by (pod)",
     "legendFormat": "{{pod{ '}}' }}"
    }
   ]
  },
  {
   "title": "Processes from the selected NODE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process present on node @ the end of time range",
     "type": "table-old",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",node=~\"$node_selected\"}[10m])) by (node,pod,id)",
       "legendFormat": "{{id{ '}}' }} "
      },
      {
       "expr": "sum (rate (container_memory_working_set_bytes{id!=\"/\",node=~\"$node_selected\"}[10m])) by (node,pod,id)",
       "legendFormat": "{{id{ '}}' }} "
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",node=~\"$node_selected\"}[10m])) by (node,pod,id)",
       "legendFormat": "{{id{ '}}' }} "
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{id!=\"/\",node=~\"$node_selected\"}[10m])) by (pod,node,id)",
       "legendFormat": "{{id{ '}}' }} "
      }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Node CPU usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[10m])) by (node) / sum (machine_cpu_cores{}) by (node) *100) ",
     "legendFormat": "{{node{ '}}' }}"
    }
   ]
  },
  {
   "title": "Node memory usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{id=\"/\"}) by (node) / sum (machine_memory_bytes{}) by (node) * 100)\r\n> 71",
     "legendFormat": "{{node{ '}}' }}"
    }
   ]
  },
  {
   "title": "Node filesystem usage percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\"}) by (node) * 100) > 30",
     "legendFormat": "{{node{ '}}' }}"
    }
   ]
  }
 ]
}