{
 "title": "1. Log & Trace chain",
 "tags": [ "SERVICE_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>LOG & TRACE chain from POD to elastic search</span>\n</div>"
   }
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pods writing logs - Top 10",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{mon_cluster=\"infra\"} | logfmt"
    }
   ]
  },
  {
   "title": "Pods writing TRACES - Top 10",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 19, "w": 6, "x": 17, "y": 3 },
   "options": {
    "content": "\n# Note\n\nThe two tables on the left show POD contribution to LOG & TRACE at the END of the chain.\nThey provide a rough idea of repartition only."
   }
  },
  {
   "title": "LOG / per level - Top 10",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:962",
       "fake": true,
       "field": "header.level.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:960", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "header.timestamp"
    }
   ]
  },
  {
   "title": "LOG / per file - Top 10",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:962",
       "fake": true,
       "field": "header.file.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:960", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "header.timestamp"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Task count [1h] / per POD & task",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "task.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 38, "w": 4, "x": 17, "y": 33 }, "options": { "content": "\n" } },
  {
   "title": "Fluentbit Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"fluentbit.*\", image!=\"\",container_name!=\"POD\"}) by (container_name, pod, node)",
     "legendFormat": "{{node{ '}}' }} / {{pod{ '}}' }} "
    }
   ]
  },
  {
   "title": "Fluentbit Pods CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"fluentbit.*\", container!=\"POD\"}[10m])) by (pod, container, node)\n\n",
     "legendFormat": "{{node{ '}}' }} / {{pod{ '}}' }} "
    }
   ]
  },
  {
   "title": "FLUENTBIT -> KAFKA / message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{topic=~\"fluent.*\"}[10m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "FLUENTD buffer queue length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time(fluentd_output_status_buffer_total_bytes[1m])",
     "legendFormat": "{{pod{ '}}' }}"
    }
   ]
  },
  {
   "title": "TRACE total count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:443",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:441", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "header.timestamp"
    }
   ]
  },
  {
   "title": "Kafka Lags on fluentd group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"fluentd.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "TRACE count on elasticsearch-trace (per hour)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "header.mission.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1h", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "LOG count on elasticsearch-log (per hour)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:72",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "1h", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:69", "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "*",
     "timeField": "header.timestamp"
    }
   ]
  }
 ]
}