{
 "title": "1. RS / Function 1 alerts",
 "tags": [
  "OPS_MANAGER_ENG",
  "FinOps"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "Template", "query": "MONITORING_FINOPS_machineUsage" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 1, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>Reference System / Function 1</s\n  pan>\n</div>"
   }
  },
  {
   "title": "Bucket Size (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{bucket=~\".*\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Function 1 monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Bucket Size (stacked)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{bucket=~\".*input\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Size (stacked)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{bucket=~\"rs-f1.*\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "SDP delivery check",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_total{bucket=~\"rs.*.*input\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "archive / index / delivery",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(MONITORING_FINOPS_objects_total{bucket=~\"rs-f1.*\"}[1h])",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "SDP delivery check / size variation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": " rate(MONITORING_FINOPS_objects_size_sum_bytes{bucket=~\"rs.*.*input\"}[2h]) ",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Size (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{bucket=~\"rs.*input\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}