{
 "title": "1. Sentinel-1 / Level-0 processing (v2)",
 "tags": [ "PROCESSING_ENG" ],
 "time": { "from": "2022-03-18T13:59:59.000Z", "to": "2022-04-30T23:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">Sentinel-1 Level-0 processing</h1>\n</center>"
   }
  },
  {
   "title": "TRACE (to ease selection period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  { "title": "AIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "AIO trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:*-aio-*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:*-aio-* AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND task.status:OK AND kubernetes.pod_name.keyword:*l0-aio*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MetadaCatalog -> AIO Production trigger / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-aio-production-trigger\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "AIO JobGenerator OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND kubernetes.pod_name.keyword:*-aio-*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO JobGenerator NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND kubernetes.pod_name.keyword:*-aio-* AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO JobGenerator / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      {
       "$$hashKey": "object:116",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:114",
       "field": "task.duration_in_seconds",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND task.status:OK AND kubernetes.pod_name.keyword:*l0-aio*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO Production trigger -> AIO Preparation Worker LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-aio-ipf-preparation-worker\" }) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "AIO OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:\"s1pro-l0-aio-ipf-execution-worker-0\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:*-aio-* AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO JobProcessing  / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND task.status:OK AND kubernetes.pod_name.keyword:*-aio-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AIO Preparation Worker -> Execution Worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-aio-ipf-execution-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "L0ASP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "L0ASP trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:*-l0-asp-*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:*-l0-asp-* AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-l0-asp-production-trigger-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Production trigger -> Preparation worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-asp-ipf-preparation-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "L0ASP Preparation Worker OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND kubernetes.pod_name.keyword:*-l0-asp-*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Preparation W NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND kubernetes.pod_name.keyword:*-l0-asp-*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Preparation Worker duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND task.status:OK AND kubernetes.pod_name.keyword:*l0-asp*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Production trigger -> Preparation worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-asp-ipf-preparation-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "L0ASP Execution W OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Execution W NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Execution Worker duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP Preparation Worker -> Execution Worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-asp-ipf-execution-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "L0ASP ObsWrite  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP ObsWrite  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP WRITE duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP ObsRead  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP ObsRead  ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP READ duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-l0-asp-ipf-execution-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Errors logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "AIO NOK",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 48 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:*-aio-*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0ASP NOK",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "L0ASP Execution W NOK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}