{
 "title": "1. Sentinel-1 Performance (v2)",
 "tags": [ "PI_ENG" ],
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-28T23:59:59.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            Sentinel-1 Performance (v2) </h1>\n</center>"
   }
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "chunks S1 available at station",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 1, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip*\") AND NOT (kubernetes.container_name:\"s1pro-ingestion-xbip-s3-trigger\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "chunks S1 available at station",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip*\") AND NOT (kubernetes.container_name:\"s1pro-ingestion-xbip-s3-trigger\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "S1 chunks stats INGESTED",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 1, "y": 13 },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "productName.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "missionId:\"S1\"",
       "timeField": "insertionTime"
      }
     ]
    },
    {
     "title": "S1 chunks stats INGESTED",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "productName.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "missionId:\"S1\"",
       "timeField": "insertionTime"
      }
     ]
    },
    {
     "title": "S1 chunks stats",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "productName.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "missionId:\"S1\"",
       "timeField": "insertionTime"
      },
      {
       "alias": "total",
       "bucketAggs": [
        { "field": "header.timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip*\") AND NOT (kubernetes.container_name:\"s1pro-ingestion-xbip-s3-trigger\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "S1 chunks ingested",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "missionId:\"S1\"",
       "timeField": "insertionTime"
      },
      {
       "alias": "total",
       "bucketAggs": [
        { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip*\") AND NOT (kubernetes.container_name:\"s1pro-ingestion-xbip-s3-trigger\")",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Segment min / max date ",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "task.input.segments.mission_data_take_id",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "task.input.segments.start", "id": "4", "type": "min" },
        { "field": "task.input.segments.stop", "id": "5", "type": "max" }
       ],
       "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Completeness ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "count unique datatake FULL without HK & GP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "creationTime",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "dataTakeId.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "(NOT swathtype:HK) AND (NOT swathtype:GP) AND (productConsolidation:FULL)",
       "timeField": "insertionTime"
      }
     ]
    },
    {
     "title": "count slices L0 on PRIP",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "name", "id": "1", "type": "cardinality" }
       ],
       "query": "productFamily:L0_SLICE_ZIP",
       "timeField": "creationDate"
      }
     ]
    },
    {
     "title": "count slices L0 on PRIP",
     "type": "table",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "attr_productType_string.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "field": "name", "id": "1", "type": "cardinality" }
       ],
       "query": "productFamily:L0_SLICE_ZIP",
       "timeField": "creationDate"
      }
     ]
    },
    {
     "title": "L0ASP Execution W OK",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 5, "y": 10 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
       ],
       "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:OK",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "L0ASP Execution NOK",
     "type": "table",
     "gridPos": { "h": 12, "w": 4, "x": 9, "y": 10 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
       ],
       "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "L0ASP NOK",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-l0-asp-ipf-execution-worker-*  AND task.status:NOK",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Timeliness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "S1 timeliness",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "S1 PRIP storage date",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "PRIP L0 Slice count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S1 E2E timeliness histogram (filter <=12h)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S1 E2E timeliness histogram (filter >12h)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 slice on PRIP",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  }
 ]
}