{
 "title": "1. Sentinel-1 Performance",
 "tags": [ "PI_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            Sentinel-1 Performance</h1>\n</center>"
   }
  },
  {
   "title": "S1 chunks stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "retrieved",
     "bucketAggs": [
      { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "missionId:\"S1\"",
     "timeField": "insertionTime"
    },
    {
     "alias": "total",
     "bucketAggs": [
      { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "task.input.filenames.filename.keyword",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "message.content:*DSDB* AND task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-cgs02*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 chunks ingested",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "retrieved",
     "bucketAggs": [
      { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "missionId:\"S1\"",
     "timeField": "insertionTime"
    },
    {
     "alias": "total",
     "bucketAggs": [
      { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "task.input.filenames.filename.keyword",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "message.content:*DSDB* AND task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-cgs02*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Completeness ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "count unique datatake FULL without HK & GP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "creationTime",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "dataTakeId.keyword", "id": "1", "type": "cardinality" }
     ],
     "query": "(NOT swathtype:HK) AND (NOT swathtype:GP) AND (productConsolidation:FULL)",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "count slices L0 on PRIP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  { "title": "Timeliness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "S1 E2E timeliness histogram (filter <=12h)",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S1 E2E timeliness histogram (filter >12h)",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 slice on PRIP",
   "type": "table",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 64 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    }
   ]
  }
 ]
}