{
 "title": "2. FinOps on Orange p/f (ENG)",
 "tags": [
  "FinOps",
  "OPS_MANAGER_ENG"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Template", "query": { "query": "MONITORING_FINOPS_machineUsage" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 3, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span></s\n  pan>\n</div>\n\n <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\nMonitor platform cost (ORANGE)\n        </h1>\n</center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 2 },
   "options": {
    "content": "Objective: Provide real time monthly cost projection.\n\nInfo\n1) Blinked periods are removed from time range computation.\nAs a consequence, the computation is the same when there are missing metrics or missing metrics are replaced by an average value get on the full period.\n2) We assume that we are using 50% of SSD disk & 50% of standard disks."
   }
  },
  {
   "title": "Monthly cost projection for ORANGE P/F  (without managed service costs)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"s3.4xlarge.2\"}) * 324.29\n",
     "legendFormat": "s3.4xlarge.2"
    },
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"s3.2xlarge.2\"}) * 162.11\n",
     "legendFormat": "s3.2xlarge.2"
    },
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"c6.2xlarge.4\"}) * 259.74\n",
     "legendFormat": "c6.2xlarge.4"
    },
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"c6.xlarge.2\"}) * 109.59\n",
     "legendFormat": "c6.xlarge.2"
    },
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"m6.2xlarge.8\"}) * 342.11\n",
     "legendFormat": "m6.2xlarge.8"
    },
    {
     "expr": "sum (MONITORING_FINOPS_machineUsage {name=~\"s3.2xlarge.4\"}) *24 * 31 * 0.31185 ",
     "legendFormat": "s3.2xlarge.4 "
    },
    {
     "expr": "sum(MONITORING_FINOPS_machineUsage{name=~\"s3.large.2\"})*24 * 31* 0.0700875",
     "legendFormat": "s3.large.2"
    },
    {
     "expr": "sum(MONITORING_FINOPS_machineUsage{name=~\"s3.xlarge.2\"})*24 * 31* 0.15",
     "legendFormat": "s3.xlarge.2"
    },
    {
     "expr": "sum(MONITORING_FINOPS_machineUsage{name=~\"s3.xlarge.4\"})*24 * 31* 0.17",
     "legendFormat": "s3.xlarge.4"
    },
    {
     "expr": "(sum(MONITORING_FINOPS_objects_size_sum_bytes{}) / (1024 * 1024 * 1024)) * 0.0214875",
     "legendFormat": "Object Storage"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{})/(1024*1024*1024*1024)) *  ((0.5 * 110.0) + (0.5 * 50.0))",
     "legendFormat": "Disk"
    },
    { "expr": "500", "legendFormat": "outbound traffic" }
   ]
  },
  {
   "title": "Cost sharing",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 139 }
   ]
  },
  { "title": "Disk cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Sum of disk capacity (average on the 31d)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{})"
    }
   ]
  },
  {
   "title": "Montlhy cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{})/(1024*1024*1024*1024)) *  ((0.5 * 110.0) + (0.5 * 50.0))"
    }
   ]
  },
  { "title": "Machine cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Machines Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (MONITORING_FINOPS_machineUsage{name=~\"$Template\"}) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Machine Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum  (MONITORING_FINOPS_machineUsage{name=~\"$Template\"}) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Object Storage cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Bucket Size (stacked)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Average Object Storage Size [current]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MONITORING_FINOPS_objects_size_sum_bytes{}) "
    }
   ]
  },
  {
   "title": " S3 / storage cost / CURRENT",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(MONITORING_FINOPS_objects_size_sum_bytes{}) / (1024 * 1024 * 1024)) * 0.0214875"
    }
   ]
  },
  {
   "title": "S3 / GET [mean per day]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.name:ObsRead  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 / PUT [mean per day]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bucket Size",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "MONITORING_FINOPS_objects_size_sum_bytes{}",
     "legendFormat": "{{bucket}}"
    }
   ]
  }
 ]
}