{
 "title": "2. Sentinel-3 / Level 0 processing",
 "tags": [ "PROCESSING_ENG" ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">Sentinel-3 level-0 processing</h1>\n</center>"
   }
  },
  {
   "title": "TRACE (to ease selection period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  { "title": "ACQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ACQ trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:s1pro-s3-acq-production-trigger-0  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:s1pro-s3-acq-production-trigger-0 AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-s3-acq-production-trigger-0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MetadaCatalog -> ACQ Production trigger / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"s3-acq-production-trigger\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ACQ Preparation Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-preparation-worker-0  AND task.status:OK AND   task.name:JobGenerator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Preparation Worker NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-preparation-worker-0  AND task.status:NOK AND   task.name:JobGenerator",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ PrepareWorker / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      {
       "$$hashKey": "object:116",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:114",
       "field": "task.duration_in_seconds",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "task.event:END AND task.name:JobGenerator AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-preparation-worker-0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Production trigger -> ACQ Preparation Worker LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"s3-acq-ipf-preparation-worker\"}) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ACQ Execution Worker OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-execution-worker-0 AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Execution Worker NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-execution-worker-0 AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Execution Worker  / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-execution-worker-0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ACQ Execution Worker -> Execution Worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"s3-acq-ipf-execution-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "L0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "L0 trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:s1pro-s3-l0-production-trigger-0  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND kubernetes.pod_name.keyword:s1pro-s3-l0-production-trigger-0 AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ProductionTrigger AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-s3-l0-production-trigger-0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Production trigger -> Preparation worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"s3-l0-production-trigger\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "L0 Preparation Worker OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:TaskTableLookup AND kubernetes.pod_name.keyword:s1pro-s3-l0-ipf-preparation-worker-0  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Preparation W NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:TaskTableLookup AND kubernetes.pod_name.keyword:s1pro-s3-l0-ipf-preparation-worker-0  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Preparation Worker duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:TaskTableLookup AND kubernetes.pod_name.keyword:s1pro-s3-l0-ipf-preparation-worker-0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Production trigger -> Preparation worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"s3-l0-ipf-preparation-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "L0 Execution W OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-l0-execution-worker*  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Execution W NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-l0-execution-worker*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Execution Worker duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND task.status:OK AND kubernetes.pod_name.keyword:s1pro-s3-l0-execution-worker*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 Preparation Worker -> Execution Worker / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"l0-s3-ipf-execution-worker\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "L0 ObsWrite  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 ObsWrite ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 WRITE duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 ObsRead  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 ObsRead ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "L0 READ duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-s3-l0-execution-worker*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "ACQ Exection Worker NOK",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-acq-ipf-execution-worker-0 AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 L0 NOK",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-l0-execution-worker*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "L0 Execution W NOK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 78 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:JobProcessing AND kubernetes.pod_name.keyword:s1pro-s3-l0-execution-worker*  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}