{
 "title": "2. Sentinel-3 Performance",
 "tags": [ "PI_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            Sentinel-3 Performance</h1>\n</center>"
   }
  },
  {
   "title": "S3 chunks stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "retrieved",
     "bucketAggs": [
      { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "missionId:\"S3\"",
     "timeField": "insertionTime"
    },
    {
     "alias": "total",
     "bucketAggs": [
      { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "task.input.filenames.filename.keyword",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "message.content:*DSDB* AND task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*trigger\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 chunks stats",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "retrieved",
     "bucketAggs": [
      { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "missionId:\"S3\"",
     "timeField": "insertionTime"
    },
    {
     "alias": "total",
     "bucketAggs": [
      { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "task.input.filenames.filename.keyword",
       "id": "1",
       "type": "cardinality"
      }
     ],
     "query": "message.content:*DSDB* AND task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*trigger\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Completeness ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Slices L0 / instument, class, type",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "instrumentName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "productClass.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Granules L0 / type",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "productClass.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "slice L0 on PRIP",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_L0_ZIP ",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "granules L0 on PRIP",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "OL_0_EFR",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  { "title": "Timeliness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "S3 E2E timeliness histogram (filter <4d)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 E2E timeliness histogram (filter >= 4d)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 granules PRIP <= 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 PRIP <= 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 30 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 granules PRIP > 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 PRIP > 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 L0 on PRIP",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 L0 granules on PRIP",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 50 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  }
 ]
}