{
 "title": "2. Sentinel-3 Performance (v2)",
 "tags": [ "PI_ENG" ],
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            Sentinel-3 Performance V2</h1>\n</center>"
   }
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "chunks S3 available at station",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 4 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*\")  ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "chunks S3 available at station",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger  AND (kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*\") ",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "S3 chunks stats INGESTED",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "productName.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "missionId:\"S3\"",
       "timeField": "insertionTime"
      }
     ]
    },
    {
     "title": "S3 chunks stats INGESTED",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 15, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1d", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "productName.keyword", "id": "1", "type": "cardinality" }
       ],
       "query": "missionId:\"S3\"",
       "timeField": "insertionTime"
      }
     ]
    },
    {
     "title": "S3 chunks stats",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "missionId:\"S3\"",
       "timeField": "insertionTime"
      },
      {
       "alias": "total",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*trigger\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "S3 chunks stats",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 9, "x": 10, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "retrieved",
       "bucketAggs": [
        { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "missionId:\"S3\"",
       "timeField": "insertionTime"
      },
      {
       "alias": "total",
       "bucketAggs": [
        { "field": "header.timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "task.input.filenames.filename.keyword",
         "id": "1",
         "type": "cardinality"
        }
       ],
       "query": "message.content:*DSDB* AND task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*trigger\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Completeness ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Slices L0 / instument, class, type",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "instrumentName.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "productClass.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Granules L0 / type",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 5 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "productType.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "slice L0 on PRIP",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "contentDateEnd", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "name", "id": "1", "type": "cardinality" }
     ],
     "query": "productFamily:S3_L0_ZIP ",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "granules L0 on PRIP",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 11, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "OL_0_EFR",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  { "title": "Timeliness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Slices L0 timeliness values",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "s3timeliness.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Granules L0 timeliness values",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 10, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "s3timeliness.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "S3 E2E timeliness histogram (filter <4d)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 E2E timeliness histogram (filter >= 4d)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 granules PRIP <= 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 slice PRIP <= 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 33 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 granules PRIP > 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "L0 slice PRIP > 3h",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 L0 on PRIP",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 39 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S3 L0 granules on PRIP",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 53 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "3000" }, "type": "raw_data" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    }
   ]
  }
 ]
}