{
 "title": "4. ESA questions",
 "tags": [ "ANALYSIS_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">ESA questions</h1>\n</center>"
   }
  },
  { "title": "Chunks & DSIB S1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "DSIB list",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 3 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "missionId:S1",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Chunk list S1A",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "missionId:S1 AND satelliteId:A",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Chunk list S1B",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 14 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "missionId:S1 AND satelliteId:B",
     "timeField": "insertionTime"
    }
   ]
  },
  { "title": "Chunks & DSIB S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "DSIB list S3",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "missionId:S3",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Chunk list S3A",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 25 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "missionId:S3 AND satelliteId:A",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Chunk list S3B",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 31 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "10000" }, "type": "raw_data" }
     ],
     "query": "missionId:S3 AND satelliteId:B",
     "timeField": "insertionTime"
    }
   ]
  }
 ]
}