{
 "title": "5. Kafka monitoring v2",
 "description": "Kafka resource usage and throughput",
 "tags": [ "SERVICE_ENG" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message in 10 minutes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=\"$instance\", topic=~\"$topic\"}[10m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$topic\",group!~\"console-consumer-.*\", group!~\"kafka-listener-service\"}) by (group, topic) ",
     "legendFormat": "{{group}} topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=~\"$topic\"}[10m])/10) by (group, topic)",
     "legendFormat": "{{group}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{}) by ( topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group per topic",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 10, "y": 34 },
   "targets": [
    {
     "expr": "sum (kafka_consumergroup_current_offset{}) by (topic, consumergroup)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}