{
 "title": "A. RS core Ingestion",
 "tags": [ "PROCESSING_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            RS core Ingestion</h1>\n</center>"
   }
  },
  {
   "title": "TRACE (to ease selection period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "IngestionTrigger AUXIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:IngestionTrigger AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-auxip-trigger*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ingestionWorker AUXIP/ LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-auxip\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "IngestionWorker AUXIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod_name:\"s1pro-ingestion-auxip*worker\" AND task.event:END AND task.name:IngestionWorker AND task.status:OK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IngestionWorker AUXIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod_name:\"s1pro-ingestion-auxip*worker\" AND task.event:END AND task.name:IngestionWorker AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IngestionWorker AUXIP duration ",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      {
       "$$hashKey": "object:116",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:114",
       "field": "task.duration_in_seconds",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "task.event:END AND task.name:IngestionWorker AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-auxip-worker*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Metadata Catalog AUXIP / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"metadata-catalogs\", topic=~\".*aux.*\" }) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "XBIP Ingestion S1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "S1 IngestionTrigger XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:IngestionTrigger AND task.status:OK AND header.mission:\"S1\"  AND NOT kubernetes.container_name:\"s1pro-ingestion-auxip-trigger\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionTrigger XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT kubernetes.container_name:\"s1pro-ingestion-auxip-trigger\"  AND task.event:END AND task.name:IngestionTrigger AND task.status:NOK AND  header.mission:\"S1\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionTrigger XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:IngestionTrigger AND header.mission:\"S1\" AND task.status:OK AND kubernetes.container_name:\"s1pro-ingestion-auxip-trigger\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "-",
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 26 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "S1 IngestionFilter XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S1 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\" AND task.event:END AND task.name:IngestionFilter AND task.status:OK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionFilter XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S1 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\" AND task.event:END AND task.name:IngestionFilter AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionFilter XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "header.mission:S1 AND task.event:END AND task.name:IngestionFilter AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ingestionFilter S1 XBIP/ LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip-filter\", topic=~\"t-pdgs-ingestion-jobs-xbip.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "S1 IngestionWorker XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S1 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*worker*\" AND task.event:END AND task.name:IngestionWorker AND task.status:OK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionWorker XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S1 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*worker*\" AND task.event:END AND task.name:IngestionWorker AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S1 IngestionWorker XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "header.mission:S1 AND task.event:END AND task.name:IngestionWorker AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-xbip-worker*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ingestionWorker S1 XBIP/ LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip\", topic=~\"t-pdgs-filtered-ingestion-jobs-xbip-.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "XBIP Ingestion S3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "S3 IngestionTrigger XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:IngestionTrigger AND task.status:OK  AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*trigger\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionTrigger XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*\"  AND task.event:END AND task.name:IngestionTrigger AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionTrigger XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:IngestionTrigger AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-xbip-s3*\" ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "-",
   "type": "text",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 42 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "S3 IngestionFilter XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S3 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\" AND task.event:END AND task.name:IngestionFilter AND task.status:OK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionFilter XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S3 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\" AND task.event:END AND task.name:IngestionFilter AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionFilter XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "header.mission:S3 AND task.event:END AND task.name:IngestionFilter AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-xbip*filter*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ingestionFilter S3 XBIP/ LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip-filter\", topic=~\"t-pdgs-ingestion-jobs-s3.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "S3 IngestionWorker XBIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S3 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*worker*\" AND task.event:END AND task.name:IngestionWorker AND task.status:OK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionWorker XBIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "header.mission:S3 AND kubernetes.pod_name:\"s1pro-ingestion-xbip*worker*\" AND task.event:END AND task.name:IngestionWorker AND task.status:NOK ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3 IngestionWorker XBIP duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "header.mission:S3 AND task.event:END AND task.name:IngestionWorker AND task.status:OK AND kubernetes.pod_name:\"s1pro-ingestion-xbip-worker*\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ingestionWorker S3 XBIP/ LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"ingestion-xbip\",topic=~\"t-pdgs-filtered-ingestion-jobs-s3.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "AUX ObsWrite  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-ingestion-auxip*worker\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AUX ObsWrite ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-ingestion-auxip*worker\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Error Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "IngestionWorker  NOK",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "task.event:END AND task.name:IngestionWorker AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } }
 ]
}