{
 "title": "B. RS core Compression",
 "tags": [ "PROCESSING_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            RS core Compression</h1>\n</center>"
   }
  },
  {
   "title": "TRACE (to ease selection period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ZIP trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:CompressionTrigger  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:CompressionTrigger  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:CompressionTrigger AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Catalog -> Compression Trigger / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"compression-trigger\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:CompressionProcessing  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:CompressionProcessing  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      {
       "$$hashKey": "object:116",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:114",
       "field": "task.duration_in_seconds",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "task.event:END AND task.name:CompressionProcessing",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP trigger -> ZIP LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"compression-worker\"}) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Object Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "ZIP ObsWrite  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-compression-worker-*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP ObsWrite ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-compression-worker-*\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP WRITE duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-compression-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsWrite  AND kubernetes.pod_name:\"s1pro-compression-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP ObsRead  OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-compression-worker-*\"  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP ObsRead ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-compression-worker-*\"  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ZIP READ duration & rate",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:ObsRead AND kubernetes.pod_name:\"s1pro-compression-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    },
    {
     "alias": "rate (avg over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.data_rate_mebibytes_sec", "id": "1", "type": "avg" }
     ],
     "query": "task.event:END AND task.name:ObsRead  AND kubernetes.pod_name:\"s1pro-compression-worker-*\" AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZIP NOK",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "task.event:END AND task.name:CompressionProcessing  AND task.status:NOK",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}