{
 "title": "C. RS core Distribution",
 "tags": [ "PROCESSING_ENG" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">\n            RS core Distribution</h1>\n</center>"
   }
  },
  {
   "title": "TRACE (to ease selection period)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PRIP trigger OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:PripTrigger  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PRIP trigger NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:PripTrigger  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PRIP Trigger / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "task.duration_in_seconds", "id": "1", "type": "max" }
     ],
     "query": "task.event:END AND task.name:PripTrigger AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Catalog -> PRIP Trigger / LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"prip-trigger\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "PRIP OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:PripWorker  AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PRIP NOK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:PripWorker  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PRIP / duration",
   "type": "timeseries",
   "description": "Average and rate are computed ONLY on task with status OK.",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "duration (max over 10m)",
     "bucketAggs": [
      {
       "$$hashKey": "object:116",
       "field": "header.timestamp",
       "id": "2",
       "settings": { "interval": "10m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:114",
       "field": "task.duration_in_seconds",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "task.event:END AND task.name:PripWorker AND task.status:OK",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PRIP trigger -> PRIP LAG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"prip-worker\"}) by (topic) ",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "PRIP NOK",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "task.event:END AND task.name:PripWorker  AND task.status:NOK",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "PRIP NOK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "task.event:END AND task.name:PripWorker  AND task.status:NOK",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}