{
 "title": "G. Cluster analysis (v2)",
 "tags": [ "ANALYSIS_ENG" ],
 "time": { "from": "2022-03-18T00:00:00.000Z", "to": "2022-04-30T23:59:58.000Z" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"${Namespace}\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>POD ressources consumption analysis</span>\n</div>"
   }
  },
  { "title": "CPU raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{ pod=~\"$Pod\",container!=\"\", resource=\"cpu\"}) by (container, pod)",
     "legendFormat": "cpu request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$Pod\", container!=\"\", resource=\"cpu\"}) by (container, pod)",
     "legendFormat": "cpu limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$Pod\", container!=\"\"}[10m])) by (container, pod)",
     "legendFormat": "cpu values"
    }
   ]
  },
  { "title": "CPU graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$Pod\", container!=\"\"}[10m])) by (container, pod)",
     "legendFormat": "{{pod}} / {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{ pod=~\"$Pod\",container!=\"\", resource=\"cpu\"}) by (container, pod)\n",
     "legendFormat": "requests {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$Pod\", container!=\"\", resource=\"cpu\"}) by (container, pod)\n",
     "legendFormat": "limits {{container}}"
    }
   ]
  },
  { "title": "Memory raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{ pod=~\"$Pod\",container!=\"\", resource=\"memory\"}) by (container, pod)",
     "legendFormat": "memory request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$Pod\", container!=\"\", resource=\"memory\"}) by (container, pod)",
     "legendFormat": "memory limit"
    },
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$Pod\", container!=\"\", container!=\"\", image!=\"\"}) by (pod,container)",
     "legendFormat": "memory values"
    }
   ]
  },
  { "title": "Memory graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$Pod\", container!=\"POD\", container!=\"\", image!=\"\"}) by (pod,container)",
     "legendFormat": "{{pod}} / {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{ pod=~\"$Pod\",container!=\"\", resource=\"memory\"}) by (container, pod)\n",
     "legendFormat": "{{pod}} / {{container}} / requests "
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$Pod\", container!=\"\", resource=\"memory\"}) by (container, pod)\n",
     "legendFormat": "{{pod}} / {{container}} / limits"
    }
   ]
  },
  {
   "title": "Export",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU & Memory",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{ pod=~\"$Pod\",container!=\"POD\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (container, pod)",
       "legendFormat": "cpu request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$Pod\", container!=\"POD\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (container, pod)",
       "legendFormat": "cpu limit"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"$Pod\", container!=\"POD\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (pod, container)",
       "legendFormat": "cpu values"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$Pod\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (container,pod)",
       "legendFormat": "Memory request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$Pod\", container!=\"\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (container,pod)",
       "legendFormat": "Memory limit"
      },
      {
       "expr": "sum(container_memory_usage_bytes{pod=~\"$Pod\", container!=\"POD\", container!=\"\", image!=\"\", pod!~\"elasticsearch-trace-snapshot-cleaner.*\", pod !~\"stash-backup-elasticsearch-.*\", pod!~\"elasticsearch-log-curator-.*\"}) by (pod,container)",
       "legendFormat": "memory values"
      }
     ]
    }
   ]
  }
 ]
}