{
 "title": "HOME v2",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": " <center>\n       \n      <h1 style=\"font-size:30px; color:#dc832b; margin:10px\">Reference System V2</h1>\n</center>"
   }
  },
  {
   "title": "PRIP content",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "S1_AUX",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:AUXILIARY_FILE_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S1_L0_SEGMENT",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:L0_SEGMENT_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S1_L0_ACN",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:L0_ACN_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S1_L0_SLICE",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:L0_SLICE_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S3_GRANULES",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_GRANULES_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S3_L0",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_L0_ZIP",
     "timeField": "creationDate"
    },
    {
     "alias": "S3_AUX",
     "bucketAggs": [
      { "field": "creationDate", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "productFamily:S3_AUX_ZIP",
     "timeField": "creationDate"
    }
   ]
  },
  {
   "title": "S1 AUX count",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "productType.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Chunks count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "missionId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "insertionTime", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "S3 AUX count",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "productType.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "Sessions ingested",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 11, "y": 20 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "3000" }, "type": "logs" }
     ],
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "S1 stations",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "3000" }, "type": "logs" }
     ],
     "query": "missionId:S1",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "title": "S3 stations",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "3000" }, "type": "logs" }
     ],
     "query": "missionId:S3",
     "timeField": "insertionTime"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<center>\n<b>    \n<p style=\"color: black ;background-color: #52be80;font-family: 'Roboto';font-size: 20px;\">Main alerts\n    <br><br></p>\n</b>\n</center>\n"
   }
  },
  { "title": "Infrastructure Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 } },
  { "title": "Service Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 } },
  { "title": "Processing Chain Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 } },
  { "title": "Performance Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 } }
 ]
}